# -- Aliases ------------------------------------------
alias a="php artisan"
alias art="php artisan"
alias migrate="php artisan migrate"
alias seed="php artisan db:seed"
alias fresh="php artisan migrate:fresh"
alias c="composer"
alias test="php artisan test"
alias routes="php artisan route:list"
alias sniff="cd /var/www/html && vendor/bin/pint --test && vendor/bin/phpstan analyse"
